# HTTP Server
server:
  contextPath: /neda # HTTP default context path
  port: 8666   # Tomcat port

# Spring properties
spring:
  application:
     name: neda # Service name
  datasource:
    url: jdbc:mysql://localhost/neda
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
