# HTTP Server
server:
  contextPath: /neda # HTTP default context path
  port: 8666   # Tomcat port

# Spring properties
spring:
  application:
     name: neda # Service name
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: STUDENT
    password: STUDENT
    driver-class-name: com.oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update